### ISSUE TITLE
discord doesn ot work

### ISSUE THREAD

**Issue by negacem925** [FeltMC/Felt-API#12]
Hi, iheard something about this being able to run forge mods on fabric whic his what i want because i want to be abl to plauy the forge versions of chaos awakens on fabric but your discord invite does not work please fix itr. I am foerm raid awakens te ad company for chaos awakens

**Comment by Trinsdar** [comment]
no one cares about you shitty modpack, and no it's not going to do that for a long time, trying to get forge running on fabric is very difficult, and will take a lot of time, time we really don't have right now.

**Comment by Trinsdar** [comment]
that said about discord, it'll get fixed when we're ready to go public
